/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLocalePicker: typeof import('./../src/components/application/AppLocalePicker.vue')['default']
    AppLogo: typeof import('./../src/components/application/AppLogo.vue')['default']
    AppProvider: typeof import('./../src/components/application/AppProvider.vue')['default']
    AppThemeToggle: typeof import('./../src/components/application/AppThemeToggle.vue')['default']
    Card: typeof import('./../src/components/card/Card.vue')['default']
    CollapseTransition: typeof import('./../src/components/Transition/CollapseTransition.vue')['default']
    EIcon: typeof import('./../src/components/icons/EIcon.vue')['default']
    ImportExcel: typeof import('./../src/components/excel/ImportExcel.vue')['default']
    LayoutMenu: typeof import('./../src/components/menu/LayoutMenu.vue')['default']
    LazyContainer: typeof import('./../src/components/lazy/LazyContainer.vue')['default']
    MenuItem: typeof import('./../src/components/menu/sideMenu/MenuItem.vue')['default']
    NumberTransition: typeof import('./../src/components/Transition/NumberTransition.vue')['default']
    ProgressBar: typeof import('./../src/components/progressBar/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../src/components/menu/sideMenu/index.vue')['default']
    SideMenuList: typeof import('./../src/components/menu/sideMenu/SideMenuList.vue')['default']
    Spin: typeof import('./../src/components/Transition/Spin.vue')['default']
    SubMenu: typeof import('./../src/components/menu/sideMenu/SubMenu.vue')['default']
    SubMenuItem: typeof import('./../src/components/menu/sideMenu/SubMenuItem.vue')['default']
    SvgIcon: typeof import('./../src/components/icons/SvgIcon.vue')['default']
    TopMenu: typeof import('./../src/components/menu/topMenu/TopMenu.vue')['default']
    TopMenuItem: typeof import('./../src/components/menu/topMenu/TopMenuItem.vue')['default']
  }
}
